### PR TITLE
fix: use budget-based rate limiting for scaling

### LINKED ISSUE #3: Asynchronous batch processing
At the moment batch processing is blocking the reconciliation loop which may have undesired side effects in some cases. For example, many batches with long delay between batches may entirely block the processing - it may still be scaling up when it's already time to scaled down, the schedule may change during the processing but won't be taken into account until the initial one is finished, etc.

Possible way to improve:
- instead of getting the entire list of workloads and chunking it upfront, start immediately reconciling them
- drop those that don't require any actions without incrementing the counter
- run the scale operation when needed, increment the counter
- once the batch size is reached, stop processing and requeue after the min(delayInterval, nextSchedule)

### PR DESCRIPTION
**Pull request by gjorgji-ts**

### CODE REVIEW

File: internal/controller/lightsoutschedule_controller.go [hunk 1]
```diff
@@ -196,43 +204,56 @@ func (r *LightsOutScheduleReconciler) Reconcile(ctx context.Context, req ctrl.Re
...
+			}
+		}
+	} else {
+		requeueAfter = timeUntilNextTransition
 	}
 
 	// Ensure minimum requeue time of 1 minute
 	if requeueAfter < time.Minute {
 		requeueAfter = time.Minute
 	}
```
Comment (pavelerofeev) [inline internal/controller/lightsoutschedule_controller.go]: Reason for this isn't very clear

**Review by pavelerofeev — DISMISSED** [review]
lgtm 👍

File: internal/controller/lightsoutschedule_controller.go (hunk 1 above)
Comment (gjorgji-ts) [reply internal/controller/lightsoutschedule_controller.go]: My idea for this was if the next transition already passed or is imminent, `time.Until()` will return zero or negative, and since `RequeueAfter: 0` tells the controller runtime `don't requeue at all` clamping to 1 minute ensures the controller always wakes back up instead of silently stalling. Not sure if this is smart, since it will add latency. But the idea for this tool is not to do rapid scale up/down, and more of scale down at night, up in the morning so I think its acceptable? @pavelerofeev

Comment (pavelerofeev) [reply internal/controller/lightsoutschedule_controller.go]: @gjorgji-ts The idea makes perfect sense, but why 1 minute and not just 1 (nanosecond)? 

On another side, looking at it again, are you sure the requeue doesn't happen immediately because of updating the status? I have a feeling Reconcile might get called twice here..

Comment (gjorgji-ts) [reply internal/controller/lightsoutschedule_controller.go]: @pavelerofeev Very good catch on both, thank you! Here is what I changed in order to fix this:

- On the 1 minute floor the idle path requeues for the next period transition, which is typically hours away. The 1 minute floor is just a defensive minimum in case `timeUntilNextTransition` computes to zero or negative (clock skew, rounding edge cases). There's no urgency when all workloads are already processed, so a longer floor avoids pointless reconcile churn. The batch path on the other hand now gets a 1 second floor so the `DelayBetweenBatches` is still honored without hot looping the API server.

- On the double reconciliation you're right, that was happening. Every `r.Status().Update()` at the end of reconcile was triggering another immediate reconcile because the controller watches all changes to the CR, including status updates. Fixed this by adding `GenerationChangedPredicate` to the watch, it tells the controller runtime to only fire on spec changes (which bump `.metadata.generation`), so status only writes are ignored. This means we no longer get a redundant second reconciliation after every status update.

**Review by pavelerofeev — APPROVED** [review]
